apiVersion: crossplane.qubership.org/v1
kind: Cassandra
metadata:
  namespace: crossplane-system
  name: cassandra
spec:
  compositionRef:
    name: cassandra
  parameters:
    storageClassName: local-path
    storageSize: 5Gi
    heapSize: 512M
