apiVersion: crossplane.qubership.org/v1
kind: Cassandra
metadata:
  # Claims in crossplane-system namespace
  namespace: crossplane-system
  name: cassandra
spec:
  # refer to the mysql composition
  compositionRef:
    name: cassandra-k8s
  parameters:
    storageClassName: local-path
    storageSize: 5Gi
    heapSize: 512M
