apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jaeger
spec:
  compositeTypeRef:
    apiVersion: crossplane.qubership.org/v1
    kind: XJaeger
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: jaeger
        base:
          apiVersion: helm.crossplane.io/v1beta1
          kind: Release
          spec:
            forProvider:
              chart:
                name: qubership-jaeger
                repository: https://ildarminaev.github.io/jaeget-helm-test
                version: "0.20.2"
              namespace: jaeger
              set:
                - name: jaeger.prometheusMonitoringDashboard
                  value: 'false'
                - name: jaeger.prometheusMonitoring
                  value: 'false'
                - name: collector.imagePullSecrets[0].name
                  value: ghcr-io-secret
                - name: query.ingress.install
                  value: 'true'
                - name: query.ingress.host
                  value: query.jaeger.localhost.localdomain
                - name: collector.ingress.install
                  value: 'true'
                - name: collector.ingress.host
                  value: collector.jaeger.localhost.localdomain
                - name: cassandraSchemaJob.host
                  value: cassandra-cluster-dc1-service.k8ssandra-operator.svc.cluster.local
                - name: jaeger.storage.type
                  value: cassandra
                - name: cassandraSchemaJob.existingSecret
                  value: "false"
                - name: cassandraSchemaJob.username
                  valueFrom:
                    secretKeyRef: 
                      key: username
                      name: cassandra-cluster-superuser
                      namespace: k8ssandra-operator
                - name: cassandraSchemaJob.password
                  valueFrom:
                    secretKeyRef: 
                      key: password
                      name: cassandra-cluster-superuser
                      namespace: k8ssandra-operator
              wait: true
            providerConfigRef:
              name: helm-provider
  - step: automatically-detect-readiness
    functionRef:
      name: function-auto-ready
