apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xopentelemetrys.crossplane.qubership.org
spec:
  group: crossplane.qubership.org
  names:
    kind: XOpenTelemetry
    plural: xopentelemetrys
  claimNames:
    kind: OpenTelemetry
    plural: opentelemetrys
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
