apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xopentelemetrys.crossplane.qubership.org
spec:
  group: crossplane.qubership.org
  names:
    kind: XOpentelemetry
    plural: xopentelemetrys
  claimNames:
    kind: Opentelemetry
    plural: opentelemetrys
  versions:
    - name: v1
      served: true
      referenceable: true
