apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: cert-manager
spec:
  forProvider:
    insecureSkipTLSVerify: true
    chart:
      name: hello
      repository: https://www.kleinloog.ch/hello-helm/
      version: 0.3.0
    namespace: cert-manager
    set:
      - name: prometheus.enabled
        value: 'true'
      - name: crds.enabled
        value: 'true'       
    values:
      service:
        type: ClusterIP
  providerConfigRef:
    name: helm-provider
