apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
  namespace: crossplane-system
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-kubernetes
