apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  #'<plural name>.<group>'
  name: xcassandras.crossplane.qubership.org
spec:
  # We will group the APIs under the crossplane.qubership.org group
  group: crossplane.qubership.org
  # Singular name and plural name of GCP DB.
  names:
    kind: XCassandra
    plural: xcassandras
  # Providing the claim API name for the product team
  claimNames:
    kind: Cassandra
    plural: cassandras
  # We will start with version v1 for the first release.
  versions:
  - name: v1
    # This is an actively served version
    served: true
    # We should be able to create composition for this version
    referenceable: true
    # OpenAPI schema
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Size will be a user input
              parameters:
                type: object
                properties:
                  namespace:
                    type: string
                required:
                - namespace
            required:
            - parameters
          status:
            type: object
            # Recourse zone - status patch parameter.
            properties:
              status:
                description: status.
                type: string
